// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXhyar_LCZz-dVH7uy1z2It9g-m8nTw98',
    appId: '1:780420300371:web:62b6c9ccc0fba8fe5790a6',
    messagingSenderId: '780420300371',
    projectId: 'fir-ea483',
    authDomain: 'fir-ea483.firebaseapp.com',
    databaseURL: 'https://fir-ea483-default-rtdb.firebaseio.com',
    storageBucket: 'fir-ea483.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpKAuK1Lh6g6mPs0A6JNY1txI3WAPWoKs',
    appId: '1:780420300371:android:b14fe6b9b570f6d25790a6',
    messagingSenderId: '780420300371',
    projectId: 'fir-ea483',
    databaseURL: 'https://fir-ea483-default-rtdb.firebaseio.com',
    storageBucket: 'fir-ea483.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANIv1YcaBv3zdnO6EiJnyfh3vOsu4cqJs',
    appId: '1:780420300371:ios:94678553eb351b1e5790a6',
    messagingSenderId: '780420300371',
    projectId: 'fir-ea483',
    databaseURL: 'https://fir-ea483-default-rtdb.firebaseio.com',
    storageBucket: 'fir-ea483.appspot.com',
    androidClientId: '780420300371-acisjqbr6kbd1jbolqfam73dhsenp0fs.apps.googleusercontent.com',
    iosClientId: '780420300371-q4if49slg3m89rbtsl1usdfcv7lt9hf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.maincasenet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANIv1YcaBv3zdnO6EiJnyfh3vOsu4cqJs',
    appId: '1:780420300371:ios:94678553eb351b1e5790a6',
    messagingSenderId: '780420300371',
    projectId: 'fir-ea483',
    databaseURL: 'https://fir-ea483-default-rtdb.firebaseio.com',
    storageBucket: 'fir-ea483.appspot.com',
    androidClientId: '780420300371-acisjqbr6kbd1jbolqfam73dhsenp0fs.apps.googleusercontent.com',
    iosClientId: '780420300371-q4if49slg3m89rbtsl1usdfcv7lt9hf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.maincasenet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXhyar_LCZz-dVH7uy1z2It9g-m8nTw98',
    appId: '1:780420300371:web:4b6908ca8d103d085790a6',
    messagingSenderId: '780420300371',
    projectId: 'fir-ea483',
    authDomain: 'fir-ea483.firebaseapp.com',
    databaseURL: 'https://fir-ea483-default-rtdb.firebaseio.com',
    storageBucket: 'fir-ea483.appspot.com',
  );
}
